import { ArrowLeft, ArrowRight, CalendarDays, CircleUserRound, FileText, LockKeyhole, Save } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { clearDemoSession, getDemoProfile, saveDemoProfile } from "./authUtils";
import { getReport } from "./reportUtils";

const REPORTS_KEY = "bizgrow-reports";
const readReports = () => { try { return JSON.parse(localStorage.getItem(REPORTS_KEY) || "[]"); } catch { return []; } };

export function ReportContact() {
  const navigate = useNavigate();
  const profile = getDemoProfile();
  const savedAnswers = (() => { try { return JSON.parse(localStorage.getItem("bizgrow-assessment") || "{}"); } catch { return {}; } })();
  const [values, setValues] = useState({ reportName: profile.name || "", email: profile.email || "", phone: profile.phone || "" });
  const [error, setError] = useState("");
  const update = (key, value) => { if (key === "phone" && /\D/.test(value)) { setError("Phone number must contain numbers only."); return; } setValues((current) => ({ ...current, [key]: key === "phone" ? value.slice(0, 10) : value })); setError(""); };
  const submit = async (event) => { event.preventDefault(); if (!values.reportName.trim()) return setError("Please enter a report name."); if (!/^\S+@\S+\.\S+$/.test(values.email)) return setError("Please enter a valid email address."); if (!/^\d{10}$/.test(values.phone)) return setError("Please enter a valid 10-digit phone number."); const report = { ...getReport(savedAnswers), contact: values, businessName: savedAnswers.businessName, reportName: values.reportName, answers: savedAnswers, date: new Date().toISOString(), id: Date.now() }; localStorage.setItem("bizgrow-latest-report", JSON.stringify(report)); localStorage.setItem(REPORTS_KEY, JSON.stringify([report, ...readReports()].slice(0, 20))); try { const health = await fetch("/api/health"); const status = await health.json(); if (status.database === "connected") await fetch("/api/reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(report) }); } catch { /* localStorage remains the offline fallback */ } navigate("/results"); };
  return <main className="report-contact-page"><div className="report-contact-shell"><Link className="back-home" to="/assessment"><ArrowLeft size={16} /> Back to assessment</Link><div className="report-contact-card"><div className="report-contact-copy"><span className="question-kicker">One last step</span><h1>Where should we send your report?</h1><p>Your personalized score and growth strategy are ready. Add your details so we know where to send them.</p><div className="contact-trust"><LockKeyhole size={17} /><span>Your information stays private and is only used for your BizGrow report.</span></div></div><form className="report-contact-form" onSubmit={submit}><label>Report Name<input required value={values.reportName} onChange={(event) => update("reportName", event.target.value)} placeholder="Alex Morgan" /></label><label>Email Address<input required type="email" value={values.email} onChange={(event) => update("email", event.target.value)} placeholder="alex@business.com" /></label><label>Phone Number<input required inputMode="numeric" maxLength="10" value={values.phone} onChange={(event) => update("phone", event.target.value)} placeholder="5551234567" /><small>Enter exactly 10 digits.</small></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="continue-button" type="submit">Send My Report <ArrowRight size={17} /></button></form></div></div></main>;
}

export function Profile() {
  const navigate = useNavigate();
  const [values, setValues] = useState(() => getDemoProfile());
  const [saved, setSaved] = useState(false);
  const update = (key, value) => setValues((current) => ({ ...current, [key]: key === "phone" ? value.replace(/\D/g, "").slice(0, 10) : value }));
  const save = (event) => { event.preventDefault(); if (!values.name?.trim() || !/^\S+@\S+\.\S+$/.test(values.email || "") || (values.phone && !/^\d{10}$/.test(values.phone))) return; saveDemoProfile(values); window.dispatchEvent(new Event("bizgrow-auth-changed")); setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <main className="inner-page profile-page"><div className="profile-header"><div><span className="question-kicker">Account settings</span><h1>Profile information</h1><p>Keep the details connected to your assessments current.</p></div><div className="profile-avatar"><CircleUserRound size={32} /></div></div><form className="profile-form" onSubmit={save}><label>Full Name<input required value={values.name || ""} onChange={(event) => update("name", event.target.value)} /></label><label>Email<input required type="email" value={values.email || ""} onChange={(event) => update("email", event.target.value)} /></label><label>Phone Number<input inputMode="numeric" maxLength="10" value={values.phone || ""} onChange={(event) => update("phone", event.target.value)} /><small>Optional. If provided, use exactly 10 digits.</small></label><div className="profile-form-actions"><button className="continue-button" type="submit"><Save size={16} /> {saved ? "Saved" : "Save Changes"}</button><button type="button" className="danger-button" onClick={() => { clearDemoSession(); window.dispatchEvent(new Event("bizgrow-auth-changed")); navigate("/"); }}>Logout</button></div></form></main>;
}

export function Reports() { const reports = readReports(); return <main className="inner-page reports-page"><div className="inner-page-header"><span className="question-kicker">Your history</span><h1>My reports</h1><p>Review the marketing assessments you have completed with BizGrow.</p></div>{reports.length ? <div className="reports-grid">{reports.map((report) => <article className="report-history-card" key={report.id}><div className="report-history-top"><FileText size={20} /><span><CalendarDays size={13} /> {new Date(report.date).toLocaleDateString()}</span></div><h2>{report.businessName || "Business assessment"}</h2><p>Report name: <b>{report.reportName || report.contact?.reportName || "Assessment report"}</b></p><div className="report-history-stats"><div><small>Marketing Score</small><strong>{report.score}/100</strong></div><div><small>Level</small><strong>{report.level}</strong></div></div><p>Recommended plan: <b>{report.plan === 12 ? "12-Month Growth" : report.plan === 6 ? "6-Month Growth" : report.plan === 3 ? "3-Month Growth" : "Monthly Growth"}</b></p><Link className="outline-button" to="/results">View Report <ArrowRight size={15} /></Link></article>)}</div> : <div className="empty-reports"><FileText size={28} /><h2>No reports yet</h2><p>Complete your free assessment to create your first personalized report.</p><Link className="primary-action" to="/assessment">Start assessment <ArrowRight size={16} /></Link></div>}</main>; }
