import { ArrowRight, BarChart3, Check, Compass, FileText, Globe2, LineChart, MapPin, Megaphone, Search, ShieldCheck, ShoppingBag, Sparkles, Target, TrendingUp, Users, WandSparkles, LayoutDashboard } from "lucide-react";
import { Link } from "react-router-dom";

const serviceData = [[Megaphone, "Social Media Marketing", "Build a recognizable presence with content that starts conversations.", ["Content calendar", "Community growth", "Monthly insights"]], [Search, "SEO", "Help the right customers find you when they are ready to choose.", ["Keyword strategy", "On-page optimization", "Search reporting"]], [LineChart, "Google Ads", "Capture high-intent demand with campaigns shaped around your goals.", ["Search campaigns", "Conversion tracking", "Bid optimization"]], [Target, "Meta Ads", "Reach future customers with creative, targeted campaigns across social.", ["Audience testing", "Creative direction", "Performance scaling"]], [Globe2, "Website Development", "Turn your digital home into a confident, high-converting first impression.", ["Responsive design", "Conversion paths", "Analytics setup"]], [FileText, "Content Marketing", "Earn attention and trust with useful ideas your audience wants to read.", ["Editorial strategy", "Expert content", "Distribution plan"]], [Users, "Lead Generation", "Create a repeatable system for turning interest into qualified conversations.", ["Offer strategy", "Landing pages", "Lead nurturing"]], [MapPin, "Local SEO", "Become easier to discover in the neighborhoods and communities you serve.", ["Google Business", "Review growth", "Local listings"]], [ShoppingBag, "E-commerce Marketing", "Make every product page, campaign, and customer touchpoint work harder.", ["Product strategy", "Shopping campaigns", "Retention flows"]]];

export function HowItWorks() { const steps = [[Compass, "01", "Tell Us About Your Business", "Share your context, audience, channels, and goals so we can see the full picture."], [FileText, "02", "Complete the Assessment", "Answer simple questions in about five minutes. Your progress saves automatically."], [BarChart3, "03", "Get Your Marketing Score", "See your score across the digital signals that matter most for your next stage."], [WandSparkles, "04", "Receive Your Growth Strategy", "Get prioritized services, a practical roadmap, and a recommended investment level."], [ShieldCheck, "05", "Choose Your Marketing Plan", "Move forward at a pace that fits your budget and the momentum you want to build."]]; return <PageFrame eyebrow="How BizGrow works" title="A clearer path from marketing questions to confident action." intro="Five focused steps turn scattered ideas into a strategy designed around your business."><div className="timeline">{steps.map(([Icon, number, title, text]) => <article className="timeline-card" key={number}><div className="timeline-number">{number}</div><div className="timeline-icon"><Icon size={21} /></div><div><h2>{title}</h2><p>{text}</p></div></article>)}</div><div className="page-cta"><div><span className="section-kicker">Ready when you are</span><h2>Start with a better question.</h2></div><Link className="primary-action" to="/assessment">Start Free Assessment <ArrowRight size={17} /></Link></div></PageFrame>; }

export function Services() { return <PageFrame eyebrow="Services" title="The right marketing mix for your next stage." intro="Start with the services your business needs now, then build from evidence instead of assumptions."><div className="service-card-grid">{serviceData.map(([Icon, title, text, benefits]) => <article className="service-card" key={title}><div className="service-icon large"><Icon size={21} /></div><h2>{title}</h2><p>{text}</p><ul>{benefits.map((benefit) => <li key={benefit}><Check size={14} />{benefit}</li>)}</ul><Link className="inline-link" to="/assessment">Learn More <ArrowRight size={15} /></Link></article>)}</div></PageFrame>; }

const pricing = [{ name: "Monthly", price: "$49", label: "Flexible foundation", features: ["Monthly strategy review", "One priority channel", "Progress dashboard"] }, { name: "3 Months", price: "$129", label: "Build momentum", features: ["Quarterly growth plan", "Two priority channels", "Monthly performance review"] }, { name: "6 Months", price: "$239", label: "Recommended growth", features: ["Integrated marketing strategy", "Four priority channels", "Biweekly optimization"] }, { name: "12 Months", price: "$399", label: "Long-term partner", features: ["Full-funnel strategy", "Ongoing channel support", "Quarterly planning sessions"] }];
export function Pricing() { return <PageFrame eyebrow="Pricing" title="Choose the support that matches your ambition." intro="Every plan starts with the same clarity. Choose how much momentum you want to build together."><div className="pricing-grid">{pricing.map((plan) => <article className={`pricing-card ${plan.name === "6 Months" ? "featured" : ""}`} key={plan.name}>{plan.name === "6 Months" && <span className="best-badge">Most popular</span>}<span className="plan-label">{plan.label}</span><h2>{plan.name}</h2><strong>{plan.price}<small>/mo</small></strong><ul>{plan.features.map((feature) => <li key={feature}><Check size={14} />{feature}</li>)}</ul><Link className={plan.name === "6 Months" ? "primary-action" : "outline-button"} to="/contact">Get Started <ArrowRight size={15} /></Link></article>)}</div><p className="pricing-note"><ShieldCheck size={15} /> No fake payment processing. Your assessment helps us recommend the right fit before any conversation.</p></PageFrame>; }

export function About() { return <PageFrame eyebrow="About BizGrow" title="Better marketing starts with a better understanding of your business." intro="BizGrow is a digital marketing assessment and growth platform for small business owners who want clarity before they invest."><div className="about-grid"><article><Sparkles size={22} /><h2>What we do</h2><p>We translate the moving parts of digital marketing into a score, a set of priorities, and a practical growth strategy you can understand.</p></article><article><Target size={22} /><h2>Why we created it</h2><p>Small business owners are asked to be everywhere at once. BizGrow exists to help you decide what matters most right now.</p></article><article><TrendingUp size={22} /><h2>Our approach</h2><p>Context first, recommendations second. We use your answers and transparent scoring rules to keep every recommendation grounded.</p></article><article><Users size={22} /><h2>Who it helps</h2><p>Local businesses, online shops, consultants, studios, and service teams ready to turn effort into consistent growth.</p></article></div><div className="about-callout"><LayoutDashboard size={25} /><div><h2>Start with your marketing baseline.</h2><p>The free assessment gives you a useful first view in less than five minutes.</p></div><Link className="primary-action" to="/assessment">Take the assessment <ArrowRight size={16} /></Link></div></PageFrame>; }

export function Contact() { const submit = (event) => { event.preventDefault(); event.currentTarget.reset(); }; return <PageFrame eyebrow="Contact" title="Let’s make your next marketing decision clearer." intro="Tell us where you are starting and we will help you find the most useful next step."><div className="contact-page-grid"><form className="contact-form" onSubmit={submit}><label>Full Name<input required placeholder="Alex Morgan" /></label><label>Business Name<input required placeholder="Northstar Studio" /></label><div className="form-columns"><label>Email<input required type="email" placeholder="alex@business.com" /></label><label>Phone<input required type="tel" placeholder="+1 555 000 0000" /></label></div><label>Message<textarea required rows="5" placeholder="How can we help your business grow?" /></label><button className="primary-action" type="submit">Send Message <ArrowRight size={16} /></button></form><aside className="contact-info"><div className="contact-info-icon"><Globe2 size={22} /></div><h2>Talk to a growth guide.</h2><p>Questions about your score, services, or a plan? We are here to make the next conversation useful.</p><a href="mailto:hello@bizgrow.co">hello@bizgrow.co</a><span>Monday–Friday, 9am–5pm</span><Link className="outline-button" to="/assessment">Book through assessment <ArrowRight size={15} /></Link></aside></div></PageFrame>; }

export function Dashboard() { const profile = JSON.parse(localStorage.getItem("bizgrow-demo-user") || "{}"); return <PageFrame eyebrow="Your workspace" title={profile.name ? `Good to see you, ${profile.name.split(" ")[0]}.` : "Your growth workspace."} intro="Keep your score, priorities, and next actions in one calm place."><div className="dashboard-grid"><article className="dashboard-score"><span className="muted-label">Marketing Score</span><strong>72<span>/100</span></strong><p>Promising foundation</p><Link className="inline-link" to="/results">View full results <ArrowRight size={15} /></Link></article><article className="dashboard-card"><div className="dashboard-card-title"><h2>Next best actions</h2><span>3 priorities</span></div><ul className="dashboard-list"><li><span><Check size={14} /></span> Clarify your ideal customer message</li><li><span><Check size={14} /></span> Create a repeatable SEO rhythm</li><li><span><Check size={14} /></span> Measure every campaign conversion</li></ul></article><article className="dashboard-card"><div className="dashboard-card-title"><h2>Recommended plan</h2><Sparkles size={17} /></div><h3>6-Month Growth</h3><p>Build the foundation, test the right channels, and optimize with evidence.</p><Link className="outline-button" to="/pricing">Review plans <ArrowRight size={15} /></Link></article></div></PageFrame>; }

function PageFrame({ eyebrow, title, intro, children }) { return <main className="inner-page"><div className="inner-page-header"><span className="question-kicker">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></div>{children}</main>; }
