import { ArrowRight, BarChart3, Check, ChevronRight, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const metrics = [["Digital Presence", "78%", "blue"], ["Social Media", "65%", "purple"], ["Advertising", "48%", "orange"], ["SEO", "55%", "blue"], ["Business Readiness", "82%", "purple"]];

function AnalyticsPreview() { return <div className="analytics-wrap"><div className="analytics-glow" /><div className="analytics-card"><div className="analytics-head"><div><span className="live-dot" />Your marketing snapshot</div><button aria-label="More options">•••</button></div><div className="score-row"><div><span className="muted-label">Marketing Score</span><strong>72<span>/100</span></strong><small><span className="up">↗ 12%</span> since last assessment</small></div><div className="score-ring"><span>72</span><small>Good</small></div></div><div className="metric-list">{metrics.map(([label, value, color]) => <div className="metric" key={label}><div><span>{label}</span><strong>{value}</strong></div><div className="metric-track"><i className={color} style={{ width: value }} /></div></div>)}</div><div className="recommendation"><div className="spark-icon"><Sparkles size={15} /></div><div><span>Recommended plan</span><strong>6-Month Growth</strong></div><ChevronRight size={17} /></div></div></div>; }

function Hero() { return <><main className="home-page"><section className="hero" id="home"><div className="hero-copy"><div className="eyebrow"><span>✦</span> The clarity your growth needs</div><h1>Discover the right <em>digital marketing</em> strategy for your business.</h1><p className="hero-text">Answer a few simple questions and get a personalized marketing score, growth strategy, recommended services, and the right plan for your business.</p><div className="hero-actions"><Link className="primary-action" to="/assessment">Start Free Assessment <ArrowRight size={17} /></Link><Link className="text-action" to="/how-it-works">Explore How It Works <ArrowRight size={16} /></Link></div><div className="hero-note"><span className="check-circle"><Check size={12} /></span> Free to start <span className="note-sep">•</span> Takes less than 5 minutes</div></div><AnalyticsPreview /></section><section className="trust-strip"><span>Built for ambitious small businesses</span><div><span><BarChart3 size={14} /> DATA-LED</span><span>SMALL BUSINESS FIRST</span><span>STRATEGY WITHOUT THE GUESSWORK</span></div></section><section className="home-bottom-cta"><span className="section-kicker">Your next chapter starts here</span><h2>Make your marketing spend count.</h2><Link className="primary-action" to="/assessment">Get my marketing score <ArrowRight size={17} /></Link></section></main><footer><Link className="logo" to="/"><span className="logo-mark">B</span>BizGrow</Link><span>Clarity for your next stage of growth.</span><span>© 2025 BizGrow</span></footer></>; }
export default Hero;
