import { ArrowRight, Check, ChevronRight, CircleAlert, Download, Gauge, RefreshCw, Sparkles, Target, TrendingUp } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";

const STORAGE_KEY = "bizgrow-assessment";
const plans = [{ name: "Monthly", price: "$49", note: "Flexible month to month", months: 1 }, { name: "3 Months", price: "$129", note: "Build early momentum", months: 3 }, { name: "6 Months", price: "$239", note: "Best for lasting growth", months: 6, best: true }, { name: "12 Months", price: "$399", note: "Maximum growth partner", months: 12 }];
const scoreValue = (answer, options) => Math.max(0, options.indexOf(answer) + 1) * (100 / options.length);

function getReport(answers) {
  const parts = [scoreValue(answers.website, ["I don't have one", "It needs work", "It works well", "It drives leads"]), scoreValue(answers.socialMedia, ["Not active yet", "Occasionally", "Consistently", "Very active"]), scoreValue(answers.advertising, ["Never", "Tried it once", "Run it occasionally", "Run it consistently"]), scoreValue(answers.seo, ["Not sure where to start", "Some basics in place", "Working on it", "A strong focus"]), scoreValue(answers.targetCustomers, ["I need help defining them", "I have a general idea", "Well defined", "Very specific and researched"])];
  const score = Math.round(parts.reduce((sum, item) => sum + (Number.isNaN(item) ? 45 : item), 0) / parts.length);
  const level = score >= 75 ? "Growth ready" : score >= 55 ? "Promising foundation" : "Early opportunity";
  const strengths = [answers.businessType ? `${answers.businessType} businesses have a clear path to focused growth.` : "You have a clear reason to invest in growth.", answers.targetCustomers?.includes("defined") || answers.targetCustomers?.includes("specific") ? "Your audience is well defined, which makes campaigns more efficient." : "You are thinking intentionally about who you want to reach.", answers.marketingGoals ? `Your focus on ${answers.marketingGoals.toLowerCase()} gives the plan a measurable direction.` : "You have a meaningful growth goal."];
  const weaknesses = [answers.website === "I don't have one" || answers.website === "It needs work" ? "Your website is the highest-impact digital presence opportunity." : "Your conversion journey could be tested and improved.", answers.seo === "Not sure where to start" ? "SEO is an untapped source of sustainable discovery." : "Your organic visibility can become more consistent.", answers.advertising === "Never" ? "Paid campaigns are a chance to reach high-intent customers faster." : "Channel performance would benefit from clearer measurement."];
  const recommended = score < 55 ? ["Website & local SEO foundation", "Social media content system", "Conversion-focused messaging"] : score < 75 ? ["SEO and content growth", "Lead generation campaigns", "Analytics and conversion tracking"] : ["Integrated campaign strategy", "Performance optimization", "Retention and referral growth"];
  const plan = answers.budget === "$3,000+" || score >= 75 ? 12 : score >= 55 ? 6 : 3;
  return { score, level, strengths, weaknesses, recommended, parts, plan };
}

function Report() {
  const navigate = useNavigate();
  let answers = {}; try { answers = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}"); } catch { answers = {}; }
  const report = getReport(answers);
  const breakdown = [["Digital Presence", report.parts[0], "blue"], ["Social Media", report.parts[1], "purple"], ["Advertising", report.parts[2], "orange"], ["SEO", report.parts[3], "blue"], ["Audience clarity", report.parts[4], "purple"]];
  const selectedPlan = plans.find((plan) => plan.months === report.plan) || plans[2];

  return <main className="report-page"><div className="report-shell"><div className="report-header"><div><span className="question-kicker">Your personalized BizGrow report</span><h1>{answers.name ? `${answers.name.split(" ")[0]}, here is your growth picture.` : "Here is your growth picture."}</h1><p>Based on your answers, you have a <strong>{report.level.toLowerCase()}</strong> and a clear set of next moves.</p></div><button className="outline-button" onClick={() => window.print()}><Download size={16} /> Save report</button></div>
    <section className="report-score-grid"><div className="big-score"><div className="score-ring large"><span>{report.score}</span><small>/100</small></div><div><span className="muted-label">Marketing score</span><h2>{report.level}</h2><p>There is a strong opportunity to make your efforts more consistent and measurable.</p></div></div><div className="report-highlight"><Sparkles size={18} /><div><span>Recommended subscription</span><strong>{selectedPlan.name} Growth</strong><p>{selectedPlan.note}</p></div></div></section>
    <section className="report-content"><div className="report-main"><ReportBlock icon={<TrendingUp />} title="Your strengths" tone="green"><ul>{report.strengths.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul></ReportBlock><ReportBlock icon={<CircleAlert />} title="Biggest opportunities" tone="orange"><ul>{report.weaknesses.map((item) => <li key={item}><Target size={15} />{item}</li>)}</ul></ReportBlock><div className="report-block breakdown-block"><div className="block-title"><Gauge size={18} /><h3>Score breakdown</h3></div>{breakdown.map(([label, value, color]) => <div className="breakdown-row" key={label}><div><span>{label}</span><strong>{Math.round(value)}%</strong></div><div className="breakdown-track"><i className={color} style={{ width: `${value}%` }} /></div></div>)}</div></div><aside className="roadmap"><span className="section-kicker">Your action plan</span><h2>3-month roadmap</h2><Roadmap number="01" title="Set your foundation" text="Clarify your message, audience, and website conversion path." /><Roadmap number="02" title="Build your visibility" text="Create a repeatable content and SEO rhythm around your expertise." /><Roadmap number="03" title="Create momentum" text="Test focused campaigns, measure results, and double down on what works." /></aside></section>
    <section className="recommended-services"><div><span className="section-kicker">Recommended for you</span><h2>Services to prioritize</h2></div><div className="service-pills">{report.recommended.map((item) => <span key={item}><Check size={14} />{item}</span>)}</div></section>
    <section className="plans" id="pricing"><div className="section-heading"><div><span className="section-kicker">Choose your pace</span><h2>A plan that grows with you.</h2></div><p>Your recommendation is highlighted based on your score and stated budget.</p></div><div className="plan-grid">{plans.map((plan) => <div className={`plan-card ${plan.months === selectedPlan.months ? "featured" : ""}`} key={plan.name}>{plan.best && <span className="best-badge">Best value</span>}<h3>{plan.name}</h3><strong>{plan.price}<small>/mo</small></strong><p>{plan.note}</p><button onClick={() => navigate("/assessment")}>{plan.months === selectedPlan.months ? "Start with this plan" : "Choose plan"}<ChevronRight size={15} /></button></div>)}</div></section>
    <div className="report-footer-actions"><Link className="back-button" to="/"><ArrowRight size={16} className="rotate-icon" /> Back to BizGrow</Link><button className="text-action" onClick={() => { localStorage.removeItem(STORAGE_KEY); navigate("/assessment"); }}><RefreshCw size={15} /> Retake assessment</button></div>
  </div></main>;
}

function ReportBlock({ icon, title, tone, children }) { return <div className={`report-block ${tone}`}><div className="block-title">{icon}<h3>{title}</h3></div>{children}</div>; }
function Roadmap({ number, title, text }) { return <div className="roadmap-step"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>; }

export default Report;
